name: Run pytest

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    name: Run test codes

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: update pip
      run: pip install -U pip

    - name: Install libraries from pip
      run: pip install -r requirements.txt

    - name: run pytest
      run: pytest
      working-directory: ./tests
